site_name: "SPARQL-Fun templates"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
docs_dir: docs
nav:
  - Readme: home.md
  - Endpoints: endpoints.md
  - Index: index.md
site_url: https://linkml.github.io/sparqlfun/
repo_url: https://github.com/linkml/sparqlfun/
